### ISSUE TITLE
Showing up in creation and edit form

### ISSUE THREAD

**Issue by tfortier** [treeStoneIT/nova-html#1]
First of all, thank you very much I was looking at weird ways to achieve something similar yesterday so great timing!

Now, I know it's clearly stated in the readme that this will only work on index and detail view but I was wondering what it would take to make it work in creation and editing form also?

I need this field not only to show what's stored in the database but also to insert "instructions" about certain fields as they are edited so having it compatible with all forms would be great. I'm not against trying to do it myself and providing a PR, but I was wondering if that kind of thing would interest you?

**Comment by bomshteyn** [comment]
Hi @tfortier ,

I don't think It would be hard, i was just doing it for what i needed in a current project :-)

Feel free to submit a PR.

**Comment by bomshteyn** [comment]
I am just thinking a bit more about this, can't you use a regular textarea for the entry form?

so in the model you would do the following:
```
Html::make('Your Field Label','your_field')
Textarea::make('Your Field Label','your_field')->onlyOnForms()
```

**Comment by tfortier** [comment]
Well, what I'm trying to achieve is to have a block of HTML above a weird input field to remind admins about what goes into that vield. In essence it's not a field I require but pure HTML.  

My instinct was to have some sort of "fake" field within my resource so that the instruction box would show up right above the problem field. The more I think of it the more it feels like I'm perverting this fieldtype.

**Comment by bomshteyn** [comment]
Oh... Did you try appending `->help('Your custom help text')`

**Comment by tfortier** [comment]
No, I guess I missed that part of the doc *facepalm*

**Comment by tfortier** [comment]
Well, after some testing, same idea but more restrictive canvas. I'll start looking in that direction though. Thanks for showing that trick to me :)
